name: Deploy To Glitch
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy To Glitch
        uses: kanadgupta/glitch-sync@main
        with:
          auth-token: '${{ secrets.AUTHTOKEN }}'
          project-id: '${{ secrets.PROJECT_ID }}'